---
# our settings for sqlalchemy.create_engine
sa:
    url: mysql+aiomysql://root:secret@db/chat
    echo: False
    future: True

# our settings for tornado.we.Application
tornado:
    cookie_name: chat-user
    cookie_secret: I do like your hat.
    login_url: /login

redis:
    topic_name: chat-topic
    redis_url: redis://redis
